on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

name: CI

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            channel: 1.59.0
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            channel: stable
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            channel: beta
          - os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            channel: nightly
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust Toolchain
        run: |
          rustup default "$TOOLCHAIN"
          rustup update "$TOOLCHAIN"
        env:
          TOOLCHAIN: ${{ matrix.channel }}-${{ matrix.target }}

      - name: Build and Test (Debug, No Default Features)
        run: cargo test --no-default-features

      - name: Build and Test (Debug, enable_unstable_features_that_may_break_with_minor_version_bumps)
        run: cargo test --no-default-features --features enable_unstable_features_that_may_break_with_minor_version_bumps

      - name: Build and Test (Debug, serde)
        run: cargo test --no-default-features --features serde

      - name: Build and Test (Release, All Features)
        run: cargo test --release --all-features

      - name: Build and Test (Minimal Versions, All Features)
        if: matrix.channel == 'nightly'
        run: cargo test --all-features -Z minimal-versions

  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check for broken intra-doc links
        run: cargo doc --document-private-items

  # This is a hack so we don't have to gate PRs on each element of the build matrix.
  build-and-test-succeeded:
    name: Build and Test Succeeded
    needs: [build-and-test, lint]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

  release:
    name: Release
    needs: build-and-test-succeeded
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check
        id: check
        run: |
          set -euo pipefail

          TAG_NAME="v$(cargo metadata --format-version=1 | jq -er '.resolve.root as $root | .packages[] | select(.id==$root) | .version')"

          if git ls-remote --exit-code origin "refs/tags/$TAG_NAME"
          then
            echo "publish=false" >> "$GITHUB_OUTPUT"
          else
            echo "publish=true" >> "$GITHUB_OUTPUT"
            echo "tag_name=$TAG_NAME" >> "$GITHUB_OUTPUT"
          fi

      - name: Cargo Publish
        if: steps.check.outputs.publish == 'true'
        run: |
          cargo publish --token "$CRATES_IO_TOKEN"
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

      - name: Create GitHub Release
        if: steps.check.outputs.publish == 'true'
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.check.outputs.tag_name }}
          release_name: ${{ steps.check.outputs.tag_name }}
          draft: false
          prerelease: false
